### ISSUE TITLE
Gitweb-1.7.10.4 > CSS labels changed and won't work

### ISSUE THREAD

**Issue by Silmerias** [kogakure/gitweb-theme#35]
1:1.7.10.4-1+wheezy2
Seems the css names have changed and the theme don't work anymore :(

**Comment by kogakure** [comment]
Could you please be more specific, what exactly is not working? (Maybe just add some screenshots?). I just tested the current gitweb-theme files against the gitweb version of Git 2.7.0 and can’t see any problems.

**Comment by Silmerias** [comment]
Yeah, sorry for the late answer. Here what I have after updated the wheezy with the last apt.
![capture_554](https://cloud.githubusercontent.com/assets/5228878/12531567/4dcedbec-c1fe-11e5-92a3-5c0dd85631ce.jpg)

Here the installation files and where.
![capture_555](https://cloud.githubusercontent.com/assets/5228878/12531570/5117c8e0-c1fe-11e5-81a6-1ee714c4824a.jpg)

I really don't know what happened. I had reinstalled the theme just in case somehting was bad, but nothing changed.

**Comment by Silmerias** [comment]
![capture_556](https://cloud.githubusercontent.com/assets/5228878/12531592/e6ed434a-c1fe-11e5-9406-5af8e7d3b46d.jpg)

**Comment by Silmerias** [comment]
![capture_558](https://cloud.githubusercontent.com/assets/5228878/12531602/273380e0-c1ff-11e5-9a1b-97f41a4c6bbc.jpg)

![capture_557](https://cloud.githubusercontent.com/assets/5228878/12531603/2ab4c2d8-c1ff-11e5-850c-0882e097adeb.jpg)

**Comment by Silmerias** [comment]
Infact, I can give you the files it will be easier for you. https://cloud.wahou.net/public.php?service=files&t=1a6941b9cedc062e1d56f2ea53ea7609

**Comment by kogakure** [comment]
Had a look on your files, but debugging without the real environment is hard … Try to find out if all paths point to the correct files. Maybe your Git installation messed something up. I suggest you open up the dev tools of your browser and check all assets. Use a DIFF tool to find out differences between the files. I think it’s not an issue of the theme, but of your environment. I’m sorry I can‘t help you further more.
