### ISSUE TITLE
Doesnt display on chrome but works fine on firefox

### ISSUE THREAD

**Issue by spicysomtam** [kogakure/gitweb-theme#36]
Maybe I missed something obvious, but the theme works fine on Firefox (which I don't use much), but doesnt work on Chrome. Tried reloading chrome and even clearing cached data. Is there something special I need to do for chrome? Using Ubuntu 16.04, apache 2.4 and chrome 56. Gitweb is the standard ubuntu install (shows up as 1:2.7.4-0ubuntu1). My desktop is Linux Mint 18.1 (chrome for linux).

**Comment by schmatzler** [comment]
What exactly doesn't work?

I have the theme installed here and it displays fine on Chrome 56:
https://git.cinelerra-cv.org/gitweb

My GIT version is the one from Debian Jessie. 2.1.4, if I'm not mistaken.

**Comment by kogakure** [comment]
I’m not aware of any browser issues. It’s just a CSS file, which should display in every browser, even old IE.

**Comment by spicysomtam** [comment]
Just tried chrome on my andriod phone; works perfectly.

**Comment by spicysomtam** [comment]
Tried to purge data for the site; that didn't work. Then deleted all content settings apart from cookies and that fixed it. Too much caching is not a good thing! Hopefully this will help someone else.
